const KEY='toolbox_inheritance_family_tree_v3';
const URL_DEFAULT='https://example.com/contact';
const COLORS=['#2f6f9f','#557ca2','#748ca3','#8f7ba6','#547a75','#7d8d58'];
const $={
people:document.getElementById('peopleList'),decedent:document.getElementById('decedentSelect'),
propertyName:document.getElementById('propertyName'),propertyMemo:document.getElementById('propertyMemo'),
propertyTarget:document.getElementById('propertyTargetShare'),propertyOwner:document.getElementById('propertyOwnerShare'),
consultationUrl:document.getElementById('consultationUrl'),family:document.getElementById('familyTree'),
heirs:document.getElementById('heirCandidatesBody'),shares:document.getElementById('shareTableBody'),
shareSummary:document.getElementById('shareSummary'),before:document.getElementById('ownershipBefore'),
bar:document.getElementById('ownershipBar'),cards:document.getElementById('ownershipCards'),notice:document.getElementById('ownershipNotice'),
notes:document.getElementById('noteList'),link:document.getElementById('consultationLink'),status:document.getElementById('statusArea'),errors:document.getElementById('errorArea'),
add:document.getElementById('addPersonButton'),run:document.getElementById('runSimulationButton'),sample1:document.getElementById('sampleBasicButton'),sample2:document.getElementById('sampleRepresentationButton'),
reset:document.getElementById('resetButton'),exportJson:document.getElementById('exportJsonButton'),importJson:document.getElementById('importJsonInput'),print:document.getElementById('printButton'),
tabs:[...document.querySelectorAll('.tab-button')],panels:[...document.querySelectorAll('.tab-panel')]
};
const state={people:[],nextId:1,decedentId:'',estate:{propertyName:'',propertyMemo:'',target:100,owner:100},consultationUrl:URL_DEFAULT,tab:'family'};
init();
function init(){bind();load();if(!state.people.length){sample('basic');msg('サンプル1を初期表示しました。');}else{render();}}
function bind(){
$.add.onclick=()=>{addPerson();render();msg('人物カードを追加しました。');};
$.sample1.onclick=()=>{sample('basic');msg('サンプル1を読み込みました。');};
$.sample2.onclick=()=>{sample('rep');msg('サンプル2を読み込みました。');};
$.run.onclick=()=>simulate(true); $.reset.onclick=()=>{localStorage.removeItem(KEY);sample('basic');msg('リセットしました。');};
$.print.onclick=()=>window.print(); $.exportJson.onclick=saveJson; $.importJson.onchange=loadJson;
$.decedent.onchange=e=>{state.decedentId=e.target.value;persist();};
[$.propertyName,$.propertyMemo,$.propertyTarget,$.propertyOwner,$.consultationUrl].forEach(el=>el.oninput=()=>{syncEstate();persist();});
$.tabs.forEach(btn=>btn.onclick=()=>setTab(btn.dataset.tab));
}
function render(){renderPeople();renderDecedent();fillEstate();setTab(state.tab);simulate(false);}
function renderPeople(){
if(!state.people.length){$.people.innerHTML='<div class="empty-state">人物が未登録です。</div>';return;}
$.people.innerHTML=state.people.map(p=>`<article class="person-card" data-id="${p.id}"><div class="person-card-header"><div class="person-card-title"><div class="person-meta"><span class="relation-badge">人物ID: ${h(p.id)}</span><span class="state-badge ${p.alive?'':'is-deceased'}">${p.alive?'生存':'死亡'}</span></div><h3>${h(p.name||'氏名未入力')}</h3><p class="mini-help">${h(hint(p))}</p></div><button type="button" class="danger-button" data-del="1">削除</button></div><div class="form-grid"><div class="field"><label>氏名</label><input data-k="name" value="${h(p.name)}"></div><div class="field"><label>性別（任意）</label><select data-k="gender">${opts([{v:'',l:'未選択'},{v:'male',l:'男性'},{v:'female',l:'女性'},{v:'other',l:'その他'}],p.gender)}</select></div><div class="field"><label>生存状況</label><select data-k="alive">${opts([{v:'alive',l:'生存'},{v:'dead',l:'死亡'}],p.alive?'alive':'dead')}</select></div><div class="field"><label>配偶者</label><select data-k="spouseId">${peopleOpts(p.id,p.spouseId,'選択しない')}</select></div><div class="field"><label>父ID</label><select data-k="fatherId">${peopleOpts(p.id,p.fatherId,'未設定')}</select></div><div class="field"><label>母ID</label><select data-k="motherId">${peopleOpts(p.id,p.motherId,'未設定')}</select></div><div class="field full"><label>備考（任意）</label><textarea data-k="notes">${h(p.notes)}</textarea></div></div></article>`).join('');
$.people.querySelectorAll('[data-id]').forEach(card=>{card.querySelectorAll('[data-k]').forEach(el=>el.oninput=el.onchange=()=>updatePerson(card.dataset.id,el.dataset.k,el.value));card.querySelector('[data-del]').onclick=()=>removePerson(card.dataset.id);});
}
function updatePerson(id,key,val){const p=find(id); if(!p)return; p[key]=key==='alive'?val==='alive':val; normalize(p); couple(id,key); persist(); render();}
function addPerson(data={}){state.people.push(normalize({id:String(state.nextId++),name:'',gender:'',alive:true,fatherId:'',motherId:'',spouseId:'',notes:'',...data})); if(!state.decedentId&&state.people[0])state.decedentId=state.people[0].id; persist();}
function removePerson(id){state.people=state.people.filter(p=>p.id!==id); state.people.forEach(p=>{if(p.fatherId===id)p.fatherId=''; if(p.motherId===id)p.motherId=''; if(p.spouseId===id)p.spouseId='';}); if(state.decedentId===id)state.decedentId=state.people[0]?state.people[0].id:''; persist(); render();}
function renderDecedent(){$.decedent.innerHTML=['<option value="">被相続人を選択してください</option>'].concat(state.people.map(p=>`<option value="${p.id}" ${p.id===state.decedentId?'selected':''}>${h(label(p))}</option>`)).join('');}
function syncEstate(){state.estate.propertyName=$.propertyName.value.trim(); state.estate.propertyMemo=$.propertyMemo.value.trim(); state.estate.target=clamp($.propertyTarget.value,100); state.estate.owner=clamp($.propertyOwner.value,100); state.consultationUrl=$.consultationUrl.value.trim()||URL_DEFAULT;}
function fillEstate(){$.propertyName.value=state.estate.propertyName; $.propertyMemo.value=state.estate.propertyMemo; $.propertyTarget.value=state.estate.target; $.propertyOwner.value=state.estate.owner; $.consultationUrl.value=state.consultationUrl;}
function simulate(show){clearMsgs(); syncEstate(); const errs=validate(); if(errs.length){error(errs); empty('入力内容を整えると結果を表示できます。'); renderNotes(); return;} const r=result(); renderFamily(r); renderHeirs(r); renderShares(r); renderOwnership(r); renderNotes(r); persist(); if(show)msg('シミュレーション結果を更新しました。');}
function validate(){const errs=[]; const ids=new Set(state.people.map(p=>p.id)); state.people.forEach(p=>{if(!p.name.trim())errs.push(`人物ID ${p.id}: 氏名を入力してください。`); ['fatherId','motherId','spouseId'].forEach(k=>{if(p[k]&&!ids.has(p[k]))errs.push(`${p.name||('人物ID '+p.id)}: ${kLabel(k)}に存在しないIDは設定できません。`); if(p[k]&&p[k]===p.id)errs.push(`${p.name||('人物ID '+p.id)}: 自分自身を${kLabel(k)}に設定できません。`);}); if(p.fatherId&&p.fatherId===p.motherId)errs.push(`${p.name||('人物ID '+p.id)}: 父IDと母IDに同じ人物は設定できません。`); if(loop(p.id))errs.push(`${p.name||('人物ID '+p.id)}: 親子関係に循環があります。`);}); if(!state.decedentId)errs.push('被相続人を選択してください。'); const d=find(state.decedentId); if(state.decedentId&&!d)errs.push('選択された被相続人が人物一覧に存在しません。'); if(d&&d.alive)errs.push('被相続人は死亡として登録してください。'); if(state.estate.target<=0||state.estate.owner<=0)errs.push('持分割合は0より大きい値を入力してください。'); return [...new Set(errs)];}
function result(){const d=find(state.decedentId), s=livingSpouse(d.id), desc=descBranches(d.id), parents=parentsOf(d.id).filter(p=>p.alive), sibs=siblingBranches(d.id); let shares=[], explanation='この簡易ルールでは相続分の目安を算出できませんでした。', group='none'; if(desc.length){group='desc'; shares=descShares(desc,s); explanation=s?'このケースでは、配偶者と子が相続人候補となるため、配偶者1/2、子系統全体で1/2が目安です。死亡した子の枝は孫が均等に承継する簡易計算です。':'このケースでは、子系統のみが相続人候補となるため、子系統で均等に整理しています。死亡した子の枝は孫が均等に承継する簡易計算です。';} else if(parents.length){group='parents'; shares=parentShares(parents,s); explanation=s?'このケースでは、配偶者と直系尊属が相続人候補となるため、配偶者2/3、直系尊属全体で1/3が目安です。':'このケースでは、直系尊属のみが相続人候補となるため、直系尊属で均等に整理しています。';} else if(sibs.length){group='sibs'; shares=sibShares(sibs,s); explanation=s?'このケースでは、配偶者と兄弟姉妹が相続人候補となるため、配偶者3/4、兄弟姉妹全体で1/4が目安です。':'このケースでは、兄弟姉妹のみが相続人候補となるため、兄弟姉妹で均等に整理しています。';} else if(s){group='spouse'; shares=[{personId:s.id,relation:'配偶者',detail:'配偶者のみ',fraction:f(1,1)}]; explanation='このケースでは、配偶者のみが相続人候補となるため、配偶者1/1が目安です。';}
const transfer=mul(f(state.estate.owner,100),f(state.estate.target,100)); const list=shares.map(x=>({...x,person:find(x.personId),propertyFraction:mul(x.fraction,transfer)}));
return {decedent:d,spouse:s,group,explanation,transfer,shares:list,candidates:candidates(d,s,desc,parents,sibs,list)};}
function candidates(d,s,desc,parents,sibs,shares){const ids=new Set(shares.map(x=>x.personId)); return state.people.filter(p=>p.id!==d.id).map(p=>({name:p.name,relation:rel(p.id,d.id),alive:p.alive?'生存':'死亡',isCandidate:ids.has(p.id)?'候補':'対象外',reason:candidateReason(p.id,s,desc,parents,sibs)}));}
function candidateReason(id,s,desc,parents,sibs){if(s&&s.id===id)return '配偶者'; if(desc.some(b=>b.heirs.some(h=>h.id===id)))return desc.some(b=>b.type==='rep'&&b.heirs.some(h=>h.id===id))?'死亡した子に代わる孫':'子'; if(parents.some(p=>p.id===id))return '直系尊属'; if(sibs.some(b=>b.heirs.some(h=>h.id===id)))return sibs.some(b=>b.type==='niece'&&b.heirs.some(h=>h.id===id))?'死亡した兄弟姉妹に代わる甥姪':'兄弟姉妹'; return '今回の簡易ルールでは該当なし';}
function renderFamily(r){const levels=[{label:'親世代',people:parentsOf(r.decedent.id)},{label:'本人世代',people:uniq([r.decedent].concat(r.spouse?[r.spouse]:[],siblingsOf(r.decedent.id)))},{label:'子世代',people:childrenOf(r.decedent.id)},{label:'孫世代',people:uniq(childrenOf(r.decedent.id).flatMap(c=>childrenOf(c.id)))}].filter(x=>x.people.length); $.family.innerHTML=levels.length?levels.map(level=>`<section class="tree-level"><p class="tree-level-title">${h(level.label)}</p><div class="tree-row">${level.people.map(p=>`<article class="tree-node ${p.id===r.decedent.id?'is-decedent':''} ${p.alive?'':'is-deceased'}"><div class="tree-node-name">${h(p.name)}</div><div class="tree-node-meta"><span class="state-badge ${p.alive?'':'is-deceased'}">${p.alive?'生存':'死亡'}</span><span class="relation-badge">${h(rel(p.id,r.decedent.id)==='本人'?'被相続人':rel(p.id,r.decedent.id))}</span></div><p class="tree-node-text">${h(p.notes||'備考なし')}</p></article>`).join('')}</div></section>`).join(''):'<div class="empty-state">家系図を表示する情報が不足しています。</div>';}
function renderHeirs(r){$.heirs.innerHTML=r.candidates.length?r.candidates.map(x=>`<tr><td>${h(x.name)}</td><td>${h(x.relation)}</td><td>${h(x.alive)}</td><td>${h(x.isCandidate)}</td><td>${h(x.reason)}</td></tr>`).join(''):'<tr><td colspan="5">候補者情報がありません。</td></tr>';}
function renderShares(r){if(!r.shares.length){$.shares.innerHTML='<tr><td colspan="5">この簡易ルールでは相続分の目安を算出できませんでした。</td></tr>'; $.shareSummary.textContent=r.explanation; return;} $.shares.innerHTML=r.shares.map(x=>`<tr><td>${h(x.person.name)}</td><td>${h(x.relation)}</td><td>${h(fr(x.fraction))}</td><td>${h(pc(percent(x.fraction)))}</td><td>${h(x.detail)}</td></tr>`).join(''); $.shareSummary.textContent=r.explanation;}
function renderOwnership(r){$.before.innerHTML=`<strong>${h(r.decedent.name)}</strong> ${h(pc(percent(r.transfer)))}<div class="mini-help">${h(state.estate.propertyName||'対象不動産')} における今回の計算対象持分です。</div>`; if(!r.shares.length){$.bar.innerHTML='<div class="empty-state">共有持分イメージを表示できません。</div>'; $.cards.innerHTML=''; $.notice.textContent='共有持分のイメージは、相続分の目安が出るケースで表示されます。'; return;} $.bar.innerHTML=r.shares.map((x,i)=>`<div class="ownership-segment" style="width:${Math.max(percent(x.propertyFraction),12)}%;background:${COLORS[i%COLORS.length]};" title="${h(x.person.name)} ${h(pc(percent(x.propertyFraction)))}">${h(x.person.name)}</div>`).join(''); $.cards.innerHTML=r.shares.map(x=>`<article class="ownership-card"><strong>${h(x.person.name)}</strong><div>${h(x.relation)} / 法定相続分の目安 ${h(fr(x.fraction))}</div><div>不動産上の持分イメージ ${h(pc(percent(x.propertyFraction)))}</div></article>`).join(''); $.notice.textContent=r.shares.length>1?'相続後は複数名の共有状態となる想定です。売却・賃貸・管理・修繕等で意思決定が複雑になる場合があります。':'今回の簡易シミュレーションでは単独承継の形です。遺産分割協議や遺言で結果が変わる可能性があります。';}
function renderNotes(r){const items=['遺言の有無や内容で結果は変わる可能性があります。','相続放棄、養子縁組、特別受益、寄与分、代襲の範囲など個別事情はこの簡易計算に反映していません。','不動産が共有になると、売却・賃貸・管理で共有者間の調整が必要になることがあります。']; if(r&&r.group==='sibs')items.push('兄弟姉妹の代襲は甥姪までの簡易対応です。'); $.notes.innerHTML=items.map(x=>`<li>${h(x)}</li>`).join(''); const href=safeUrl(state.consultationUrl||URL_DEFAULT); $.link.href=href; $.link.textContent=href==='#'?'相談先URLを入力してください':'相談先を開く';}
function empty(text){const box=`<div class="empty-state">${h(text)}</div>`; $.family.innerHTML=box; $.heirs.innerHTML='<tr><td colspan="5">結果はまだありません。</td></tr>'; $.shares.innerHTML='<tr><td colspan="5">結果はまだありません。</td></tr>'; $.shareSummary.textContent='入力後にシミュレーションを実行してください。'; $.before.innerHTML=box; $.bar.innerHTML=box; $.cards.innerHTML=''; $.notice.textContent='共有持分のイメージは結果表示後に確認できます。';}
function setTab(tab){state.tab=TAB_ORDER.includes(tab)?tab:'family'; $.tabs.forEach(b=>b.classList.toggle('is-active',b.dataset.tab===state.tab)); $.panels.forEach(p=>p.classList.toggle('is-active',p.dataset.panel===state.tab));}
function descShares(branches,s){const out=[]; if(s)out.push({personId:s.id,relation:'配偶者',detail:'配偶者は1/2の目安',fraction:f(1,2)}); const total=s?f(1,2):f(1,1); const per=div(total,branches.length); branches.forEach(b=>{const each=div(per,b.heirs.length); b.heirs.forEach(hh=>out.push({personId:hh.id,relation:rel(hh.id,state.decedentId),detail:b.type==='rep'?'死亡した子の枝を孫で均等配分':'子の枝を均等配分',fraction:each}));}); return out;}
function parentShares(parents,s){const out=[]; if(s)out.push({personId:s.id,relation:'配偶者',detail:'配偶者は2/3の目安',fraction:f(2,3)}); const total=s?f(1,3):f(1,1); const each=div(total,parents.length); parents.forEach(p=>out.push({personId:p.id,relation:rel(p.id,state.decedentId),detail:'直系尊属で均等配分',fraction:each})); return out;}
function sibShares(branches,s){const out=[]; if(s)out.push({personId:s.id,relation:'配偶者',detail:'配偶者は3/4の目安',fraction:f(3,4)}); const total=s?f(1,4):f(1,1); const per=div(total,branches.length); branches.forEach(b=>{const each=div(per,b.heirs.length); b.heirs.forEach(hh=>out.push({personId:hh.id,relation:rel(hh.id,state.decedentId),detail:b.type==='niece'?'甥姪までの簡易代襲':'兄弟姉妹で均等配分',fraction:each}));}); return out;}
function livingSpouse(id){const p=find(id); const s=p&&p.spouseId?find(p.spouseId):null; return s&&s.alive?s:null;}
function childrenOf(id){return state.people.filter(p=>p.fatherId===id||p.motherId===id);} function parentsOf(id){const p=find(id); return p?[find(p.fatherId),find(p.motherId)].filter(Boolean):[];}
function siblingsOf(id){const p=find(id); if(!p)return[]; return state.people.filter(c=>c.id!==p.id&&((p.fatherId&&c.fatherId===p.fatherId)||(p.motherId&&c.motherId===p.motherId)));}
function descBranches(id){return childrenOf(id).flatMap(c=>c.alive?[{type:'child',heirs:[c]}]:(childrenOf(c.id).filter(g=>g.alive).length?[{type:'rep',heirs:childrenOf(c.id).filter(g=>g.alive)}]:[]));}
function siblingBranches(id){return siblingsOf(id).flatMap(s=>s.alive?[{type:'sibling',heirs:[s]}]:(childrenOf(s.id).filter(c=>c.alive).length?[{type:'niece',heirs:childrenOf(s.id).filter(c=>c.alive)}]:[]));}
function rel(id,d){if(id===d)return'本人'; const x=find(d); if(!x)return'関係未判定'; if(x.spouseId===id)return'配偶者'; if(x.fatherId===id)return'父'; if(x.motherId===id)return'母'; if(childrenOf(d).some(c=>c.id===id))return'子'; if(childrenOf(d).some(c=>childrenOf(c.id).some(g=>g.id===id)))return'孫'; if(siblingsOf(d).some(s=>s.id===id))return'兄弟姉妹'; if(siblingsOf(d).some(s=>childrenOf(s.id).some(c=>c.id===id)))return'甥姪'; return'親族';}
function couple(id,key){if(key!=='spouseId')return; const src=find(id); if(!src)return; state.people.forEach(p=>{if(p.id!==src.id&&p.spouseId===src.id&&src.spouseId!==p.id)p.spouseId='';}); if(src.spouseId){const s=find(src.spouseId); if(s)s.spouseId=src.id;}}
function loop(id,seen=new Set()){if(!id)return false; if(seen.has(id))return true; const p=find(id); if(!p)return false; const next=new Set(seen); next.add(id); return [p.fatherId,p.motherId].filter(Boolean).some(pid=>loop(pid,next));}
function sample(kind){restore(kind==='rep'?{nextId:6,decedentId:'1',consultationUrl:URL_DEFAULT,estate:{propertyName:'横浜市神奈川区サンプルマンション',propertyMemo:'被相続人持分を100%と仮定',target:100,owner:100},people:[{id:'1',name:'父',gender:'male',alive:false,spouseId:'2',fatherId:'',motherId:'',notes:'被相続人'},{id:'2',name:'母',gender:'female',alive:true,spouseId:'1',fatherId:'',motherId:'',notes:''},{id:'3',name:'子A',gender:'male',alive:false,spouseId:'',fatherId:'1',motherId:'2',notes:'父より先に死亡'},{id:'4',name:'孫A1',gender:'female',alive:true,spouseId:'',fatherId:'3',motherId:'',notes:''},{id:'5',name:'孫A2',gender:'male',alive:true,spouseId:'',fatherId:'3',motherId:'',notes:''}]}:{nextId:5,decedentId:'1',consultationUrl:URL_DEFAULT,estate:{propertyName:'横浜市神奈川区○○マンション',propertyMemo:'相続整理用のサンプル',target:100,owner:100},people:[{id:'1',name:'父',gender:'male',alive:false,spouseId:'2',fatherId:'',motherId:'',notes:'被相続人'},{id:'2',name:'母',gender:'female',alive:true,spouseId:'1',fatherId:'',motherId:'',notes:''},{id:'3',name:'子A',gender:'female',alive:true,spouseId:'',fatherId:'1',motherId:'2',notes:''},{id:'4',name:'子B',gender:'male',alive:true,spouseId:'',fatherId:'1',motherId:'2',notes:''}]}); render();}
function restore(data){state.people=Array.isArray(data.people)?data.people.map(p=>normalize(p)):[]; state.nextId=Number(data.nextId)||next(state.people); state.decedentId=String(data.decedentId||''); state.estate={propertyName:String((data.estate||{}).propertyName||''),propertyMemo:String((data.estate||{}).propertyMemo||''),target:clamp((data.estate||{}).target,100),owner:clamp((data.estate||{}).owner,100)}; state.consultationUrl=String(data.consultationUrl||URL_DEFAULT); persist();}
function load(){try{const raw=localStorage.getItem(KEY); if(raw)restore(JSON.parse(raw));}catch(e){console.error(e);}}
function persist(){try{localStorage.setItem(KEY,JSON.stringify({people:state.people,nextId:state.nextId,decedentId:state.decedentId,estate:state.estate,consultationUrl:state.consultationUrl}));}catch(e){console.error(e);}}
function loadJson(e){const file=e.target.files&&e.target.files[0]; if(!file)return; const r=new FileReader(); r.onload=()=>{try{restore(JSON.parse(String(r.result||'{}'))); render(); msg('JSONを読み込みました。');}catch(_){error(['JSONの読み込みに失敗しました。']);} finally{$.importJson.value='';}}; r.readAsText(file);}
function saveJson(){const blob=new Blob([JSON.stringify({people:state.people,nextId:state.nextId,decedentId:state.decedentId,estate:state.estate,consultationUrl:state.consultationUrl},null,2)],{type:'application/json;charset=utf-8'}); const url=URL.createObjectURL(blob); dl(url,`inheritance-family-tree-${today()}.json`); URL.revokeObjectURL(url); msg('JSONをエクスポートしました。');}
function normalize(p){return {id:String(p.id||''),name:String(p.name||'').trim(),gender:String(p.gender||''),alive:Boolean(p.alive),fatherId:String(p.fatherId||''),motherId:String(p.motherId||''),spouseId:String(p.spouseId||''),notes:String(p.notes||'').trim()};}
function find(id){return state.people.find(p=>p.id===String(id))||null;} function label(p){return `${p.name||('ID'+p.id)} (${p.alive?'生存':'死亡'})`;}
function hint(p){const a=[]; if(p.fatherId)a.push(`父: ${(find(p.fatherId)||{}).name||p.fatherId}`); if(p.motherId)a.push(`母: ${(find(p.motherId)||{}).name||p.motherId}`); if(p.spouseId)a.push(`配偶者: ${(find(p.spouseId)||{}).name||p.spouseId}`); return a.length?a.join(' / '):'親子関係・配偶者関係は未設定です。';}
function peopleOpts(self,sel,empty){return opts([{v:'',l:empty}].concat(state.people.filter(p=>p.id!==self).map(p=>({v:p.id,l:label(p)}))),sel);} function opts(arr,sel){return arr.map(x=>`<option value="${h(x.v)}" ${x.v===sel?'selected':''}>${h(x.l)}</option>`).join('');}
function kLabel(k){return {fatherId:'父ID',motherId:'母ID',spouseId:'配偶者ID'}[k]||k;} function next(arr){return arr.reduce((m,p)=>Math.max(m,Number(p.id)||0),0)+1;}
function f(n,d){const g=gcd(Math.abs(n),Math.abs(d)); return {n:n/g||0,d:d/g||1};} function mul(a,b){return f(a.n*b.n,a.d*b.d);} function div(a,c){return f(a.n,a.d*c);} function gcd(a,b){return b?gcd(b,a%b):(a||1);} function fr(x){return `${x.n}/${x.d}`;} function percent(x){return x.n/x.d*100;} function pc(v){return `${Number(v).toFixed(v>=10?1:2).replace(/\.0+$/,'').replace(/(\.\d*[1-9])0+$/,'$1')}%`;}
function clamp(v,fb){const n=Number(v); return Number.isFinite(n)?Math.min(100,Math.max(0,n)):fb;} function uniq(arr){return arr.filter((p,i,a)=>p&&a.findIndex(x=>x.id===p.id)===i);} function msg(t){$.status.innerHTML=`<div class="status-message">${h(t)}</div>`;} function error(list){$.errors.innerHTML=list.map(x=>`<div class="error-message">${h(x)}</div>`).join('');} function clearMsgs(){$.status.innerHTML=''; $.errors.innerHTML='';}
function safeUrl(v){try{const u=new URL(v); return ['http:','https:'].includes(u.protocol)?u.toString():'#';}catch(_){return '#';}} function dl(url,name){const a=document.createElement('a'); a.href=url; a.download=name; document.body.appendChild(a); a.click(); a.remove();}
function today(){const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;} function h(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
